/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as BagRouteImport } from './routes/bag'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResellOrderIdRouteImport } from './routes/resell.$orderId'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellOrderIdRoute = ResellOrderIdRouteImport.update({
  id: '/resell/$orderId',
  path: '/resell/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bag': typeof BagRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wishlist': typeof WishlistRoute
  '/listing/$id': typeof ListingIdRoute
  '/product/$id': typeof ProductIdRoute
  '/resell/$orderId': typeof ResellOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bag': typeof BagRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wishlist': typeof WishlistRoute
  '/listing/$id': typeof ListingIdRoute
  '/product/$id': typeof ProductIdRoute
  '/resell/$orderId': typeof ResellOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bag': typeof BagRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wishlist': typeof WishlistRoute
  '/listing/$id': typeof ListingIdRoute
  '/product/$id': typeof ProductIdRoute
  '/resell/$orderId': typeof ResellOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bag'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/listing/$id'
    | '/product/$id'
    | '/resell/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bag'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/listing/$id'
    | '/product/$id'
    | '/resell/$orderId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bag'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/listing/$id'
    | '/product/$id'
    | '/resell/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BagRoute: typeof BagRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  WishlistRoute: typeof WishlistRoute
  ListingIdRoute: typeof ListingIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ResellOrderIdRoute: typeof ResellOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resell/$orderId': {
      id: '/resell/$orderId'
      path: '/resell/$orderId'
      fullPath: '/resell/$orderId'
      preLoaderRoute: typeof ResellOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BagRoute: BagRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  WishlistRoute: WishlistRoute,
  ListingIdRoute: ListingIdRoute,
  ProductIdRoute: ProductIdRoute,
  ResellOrderIdRoute: ResellOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
